### ISSUE TITLE
limit airsupport

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#54]
find somekind of limit for airsupport (A10, Comanche, etc.)

**Comment by iJesuz** [comment]
There are a cupple of options:
* seperate helicopter pilot slots and jet pilot slots
* event handler on pilots which decreases and increases a global counter if they get in or out of an airsupport vehicle
* create a whitelist for pilot slots:
   * database based (small file based db should be enough)
   * config file based
* (I would not recommend this point because we speak about a public server:)
we bind the airsupport slots to the jtac slot (so no jtacs no cas or something like this)

I prefer point 3.1. because we don't force every user to redownload the mission pbo file if we add a new pilot and we stop new player from spamming the ao with missles.

**Comment by iJesuz** [comment]
Idea by Maverick:

* airsupport vehicle spawned as sidemission reward

**Comment by Dorbedo** [comment]
databased version is the version we will implement

**Comment by Dorbedo** [comment]
8cc8ae64d869eeab3fa266166c9462cad44bfd37
